### ISSUE TITLE
upload shouldn't accept str

### ISSUE THREAD

**Issue by wardi** [DataShades/ckanext-files#3]
files are binary data so it doesn't make sense for the upload parameter to accept `str` as one of the types.

In particular, this line https://github.com/DataShades/ckanext-files/blob/6e9d170ad1bc7d1a53f57057a773c4c122eaf315/ckanext/files/utils.py#L375 would cause a server error if the str contains characters not in the system's default encoding.

We could force utf-8 encoding of str values passed but I think it's better to not accept any str parameters because files should always contain binary data.

The example in the readme could be changed to use a file upload instead of a str:
```bash
ckanapi action files_file_create name=hello.txt upload@<(echo 'hello world')
```
or slightly less confusing as two lines:
```bash
echo 'hello world' > myfile.txt
ckanapi action files_file_create name=hello.txt upload@myfile.txt
```

**Comment by smotornyuk** [comment]
I can think of one use-case for string. Extensions like ckanext-validation(or even ckanext-scheming) can use a textarea or any other text field for schema modifications. Then the form is submitted and value of the field is saved as a file. 

Without str support, because form cannot pass binary data in non-file field, we need to write a layer that converts text field into file

**Comment by wardi** [comment]
Seems like a niche case.

If we need a form to accept data that will be converted to a file we could add a validator to encode str to bytes e.g. as utf-8. That way the developer is choosing the encoding we're not guessing it for them.
